server:
  servlet:
    session:
      timeout: 30m
    context-path:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qa_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
        multipart:
          max-file-size: 50MB
          max-request-size: 50MB
  web:
    resources:
      static-locations: classpath:/static/,file:${upload.path}/
upload:
        path: D:/idea_projects/qa-system/uploads/

mybatis:
  mapper-locations: classpath:mapper/*.xml